#!/usr/bin/env ruby

W = 25
T = 6

input = $stdin.readlines[0].strip.chars.map(&:to_i)

layers = input.each_slice(W * T).to_a

image = layers.pop

layers.reverse.each do |layer|
  (W*T).times do |i|
    case layer[i]
    when 0
      image[i] = 0
    when 1
      image[i] = 1
    end
  end
end

image.each_slice(W).each_slice(2) do |u, l|
  if l.nil? then
    u.each do |p|
      case u
      when 0
        print " "
      when 1
        print "▀"
      end
    end
  else
    W.times do |i|
      case [u[i], l[i]]
      when [0,0]
        print " "
      when [0,1]
        print "▄"
      when [1,0]
        print "▀"
      when [1,1]
        print "█"
      end
    end
  end
  puts
end
